site_url: https://webssh.net
site_name: WebSSH
copyright: WebSSH &copy; 2012-2024<br />Like my work? <a href="https://github.com/sponsors/isontheline">Sponsors</a> and <a href="https://www.buymeacoffee.com/isontheline">Coffees</a> are welcome!
theme:
  name: material
  custom_dir: overrides
  logo: images/webssh_round.png
  favicon: images/favicon.ico
  font: false
  palette:
    scheme: preference
  features:
    - navigation.tabs
extra_css:
  - stylesheets/extra.css?20210620
extra_javascript:
  - javascripts/extra.js?20220505
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/isontheline/pro.webssh.net
    - icon: fontawesome/solid/heart
      link: https://github.com/sponsors/isontheline
    - icon: fontawesome/solid/mug-saucer
      link: https://www.buymeacoffee.com/isontheline
plugins:
  - search
  - git-revision-date-localized:
      type: date
  - redirects:
      redirect_maps:
        'documentation/changelog/15/15.0.md': 'documentation/changelog/15.md'
        'documentation/pricing-fr.md': 'documentation/pricing.md'
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - footnotes