site_url: https://webssh.net
site_name: iOS / iPadOS / macOS SSH Client - WebSSH
copyright: If you want to support my sleepless nights, you can <a href="https://www.buymeacoffee.com/arnaud.mengus">buy me a coffee</a>! <script data-name="BMC-Widget" data-cfasync="false" src="https://cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js" data-id="arnaud.mengus" data-description="Support me on Buy me a coffee!" data-message="If you want to support my sleepless nights, you can buy me a coffee!" data-color="#5F7FFF" data-position="Right" data-x_margin="18" data-y_margin="18"></script>
theme:
  name: material
  custom_dir: overrides
  logo: images/webssh.png
  favicon: images/favicon.ico
  font: false
  palette:
    scheme: preference
  features:
    - navigation.tabs
extra_css:
  - stylesheets/extra.css?20210620
extra_javascript:
  - javascripts/extra.js?20210418
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/isontheline/pro.webssh.net
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/arnaud-mengus
plugins:
  - search
  - git-revision-date-localized:
      type: date
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - footnotes