site_url: https://webssh.net
site_name: iOS / iPadOS / macOS SSH Client - WebSSH
copyright: WebSSH &copy; 2012-2021 by <a href="https://mengus.net">mengus.net</a>
theme:
  name: material
  custom_dir: overrides
  logo: images/webssh.png
  favicon: images/favicon.ico
  font: false
  palette:
    scheme: preference
  features:
    - navigation.tabs
extra_css:
  - stylesheets/extra.css?20210620
extra_javascript:
  - javascripts/extra.js?20210418
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/isontheline/pro.webssh.net
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/arnaud-mengus
    - icon: fontawesome/solid/globe
      link: https://mengus.net
plugins:
  - search
  - git-revision-date-localized:
      type: date
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - footnotes